default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "password") %>
  pool: 5

development:
  <<: *default
  database: desafio_bemobi

test:
  <<: *default
  database: desafio_bemobi_test
